plugins {
    id 'com.android.application'
}

android {
    namespace 'com.store4a.app'
    compileSdk 34

    defaultConfig {
        applicationId "com.store4a.app"
        minSdk 24
        targetSdk 34
        versionCode 7
        versionName "1.6"
    }

    signingConfigs {
        release {
            storeFile file("${rootProject.projectDir}/4astore-key.jks")
            storePassword "Store4A2026"
            keyAlias "4astore"
            keyPassword "Store4A2026"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.webkit:webkit:1.8.0'
    implementation 'com.google.android.material:material:1.10.0'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
    implementation 'androidx.core:core:1.12.0'
    implementation 'androidx.activity:activity:1.8.0'
}
